import { BookOpenCheck, CalendarCheck2, ChartNoAxesCombined, Sparkles, Target, Trophy } from "lucide-react";
import Alert from "../components/Alert.jsx";
import LoadingSpinner from "../components/LoadingSpinner.jsx";
import PageHeader from "../components/PageHeader.jsx";
import StatCard from "../components/StatCard.jsx";
import useApi from "../hooks/useApi.js";

export default function ProgressPage() {
  const { data, loading, error } = useApi("/students/progress", {});
  if (loading) return <LoadingSpinner />;
  const quizScore = Number(data.average_quiz_score || 0);
  return <section className="learning-progress-page"><PageHeader eyebrow="Learning signal" title="Progress you can act on" description="Classes, assignments, quizzes, and tutor feedback translated into a clear picture of where you are growing." /><Alert>{error}</Alert><div className="stats-grid"><StatCard icon={CalendarCheck2} label="Classes completed" value={data.completed_classes} hint="Sessions in your record" /><StatCard icon={Trophy} label="Attendance" value={`${data.attendance_percentage || 0}%`} hint="Consistency across bookings" tone="green" /><StatCard icon={BookOpenCheck} label="Assignment completion" value={`${data.completion_percentage || 0}%`} hint="Submitted and graded" tone="amber" /><StatCard icon={ChartNoAxesCombined} label="Average performance" value={`${data.average_performance || 0}%`} hint="Assignments and quizzes" tone="purple" /></div><div className="progress-studio-grid"><article className="panel progress-score-card"><div><span className="panel-eyebrow">Knowledge checks</span><h2>Your quiz signal</h2><p>One score never tells the whole story. Use this as a directional marker across every attempt.</p></div><div className="progress-ring" style={{ "--progress": `${quizScore}%` }}><span><strong>{quizScore}%</strong><small>average</small></span></div><div className="progress-score-foot"><span><Sparkles size={15} /> {data.quizzes_attempted || 0} attempts recorded</span><span><Target size={15} /> Aim for steady gains</span></div></article><article className="panel panel-wide feedback-studio"><div className="panel-heading"><div><span className="panel-eyebrow">From your mentors</span><h2>Feedback and focus</h2></div></div>{data.tutor_feedback?.length ? data.tutor_feedback.map((item) => <div className="feedback-row" key={item.title}><span><Sparkles size={15} /></span><div><strong>{item.title}</strong><p>{item.feedback}</p></div></div>) : <div className="progress-empty"><Sparkles size={20} /><p>Feedback will appear after assignments are graded.</p></div>}<div className="focus-topics"><span className="panel-eyebrow">Next focus</span><h3>Topics worth another pass</h3><div className="tag-row">{data.weak_topics?.length ? data.weak_topics.map((topic) => <span className="tag" key={topic}>{topic}</span>) : <span className="tag">Keep exploring</span>}</div></div></article></div></section>;
}
