"""Render the Mentor Market assignment diagrams as high-resolution PNGs.

The class diagram is rendered from the editable Draw.io source. The MVC
architecture diagram is created as a deterministic SVG so that all technical
labels and request-flow arrows remain exact.
"""

from __future__ import annotations

import ast
import html
from pathlib import Path
import re
import subprocess
from xml.etree import ElementTree as ET


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "documentation" / "assignment_assets"

DRAWIO_SOURCE = ROOT / "documentation" / "Mentor_Market_Class_Diagram.drawio"
DRAWIO_RENDERER_SOURCE = ROOT / "scripts" / "generate_470_a1_docx.py"
CLASS_SVG = ASSET_DIR / "mentor_market_class_diagram.svg"
CLASS_PNG = ASSET_DIR / "mentor_market_class_diagram.png"

MVC_SVG = ASSET_DIR / "mentor_market_mvc_architecture.svg"
MVC_PNG = ASSET_DIR / "mentor_market_mvc_architecture.png"

SERIF_STACK = "Times New Roman, Liberation Serif, serif"


def _times_svg_text(
    x,
    y,
    text,
    size,
    anchor="start",
    weight="normal",
    style="normal",
):
    return (
        f'<text x="{x:.2f}" y="{y:.2f}" '
        f'font-family="{SERIF_STACK}" font-size="{size}" '
        f'font-weight="{weight}" font-style="{style}" '
        f'text-anchor="{anchor}" fill="#000000">{html.escape(text)}</text>'
    )


def render_class_diagram() -> None:
    """Load the tested Draw.io exporter without importing python-docx."""
    if not DRAWIO_RENDERER_SOURCE.exists():
        raise FileNotFoundError(DRAWIO_RENDERER_SOURCE)

    source = DRAWIO_RENDERER_SOURCE.read_text(encoding="utf-8")
    tree = ast.parse(source)
    required = {
        "_mx_style",
        "_mx_geometry",
        "_drawio_text_parts",
        "_svg_text",
        "_cell_anchor",
        "_orthogonal_points",
        "_edge_label_position",
        "export_drawio_class_diagram",
    }
    selected = [
        node
        for node in tree.body
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
        and node.name in required
    ]
    found = {node.name for node in selected}
    missing = required.difference(found)
    if missing:
        raise RuntimeError(
            "Draw.io renderer is missing: " + ", ".join(sorted(missing))
        )

    namespace = {
        "ET": ET,
        "ASSET_DIR": ASSET_DIR,
        "DRAWIO_SOURCE": DRAWIO_SOURCE,
        "DRAWIO_SVG": CLASS_SVG,
        "DOMAIN_DIAGRAM": CLASS_PNG,
        "html": html,
        "re": re,
        "subprocess": subprocess,
    }
    module = ast.Module(body=selected, type_ignores=[])
    exec(compile(module, str(DRAWIO_RENDERER_SOURCE), "exec"), namespace)
    # Keep the source geometry and relationships but use the assignment's
    # serif typography for all text generated by the renderer.
    namespace["_svg_text"] = _times_svg_text
    namespace["export_drawio_class_diagram"]()

    # Add a small safety border so the bottom Lesson class cannot touch the
    # bitmap boundary.
    bordered = CLASS_PNG.with_name(f"{CLASS_PNG.stem}.bordered.png")
    subprocess.run(
        [
            "magick",
            str(CLASS_PNG),
            "-bordercolor",
            "white",
            "-border",
            "20x20",
            str(bordered),
        ],
        check=True,
    )
    bordered.replace(CLASS_PNG)


def _svg_multiline_text(
    x: int,
    y: int,
    lines: list[str],
    *,
    size: int,
    line_height: int,
    anchor: str = "middle",
    weight: str = "normal",
) -> str:
    tspans = []
    for index, line in enumerate(lines):
        dy = 0 if index == 0 else line_height
        tspans.append(
            f'<tspan x="{x}" dy="{dy}">{html.escape(line)}</tspan>'
        )
    return (
        f'<text x="{x}" y="{y}" font-family="{SERIF_STACK}" '
        f'font-size="{size}" font-weight="{weight}" '
        f'text-anchor="{anchor}" fill="#000000">'
        f'{"".join(tspans)}</text>'
    )


def _architecture_box(
    x: int,
    y: int,
    width: int,
    height: int,
    title: str,
    subtitle: str,
    lines: list[str],
    *,
    title_size: int = 31,
) -> str:
    header_height = 72
    title_y = y + 46
    subtitle_y = y + 108
    body_y = y + 160
    return "".join(
        [
            (
                f'<rect x="{x}" y="{y}" width="{width}" height="{height}" '
                'fill="#ffffff" stroke="#000000" stroke-width="3"/>'
            ),
            (
                f'<rect x="{x}" y="{y}" width="{width}" '
                f'height="{header_height}" fill="#ededed" stroke="#000000" '
                'stroke-width="3"/>'
            ),
            _svg_multiline_text(
                x + width // 2,
                title_y,
                [title],
                size=title_size,
                line_height=36,
                weight="bold",
            ),
            _svg_multiline_text(
                x + width // 2,
                subtitle_y,
                [subtitle],
                size=25,
                line_height=32,
                weight="bold",
            ),
            _svg_multiline_text(
                x + width // 2,
                body_y,
                lines,
                size=24,
                line_height=44,
            ),
        ]
    )


def _connector(
    start_x: int,
    end_x: int,
    y: int,
    label: str,
    *,
    reverse: bool = False,
) -> str:
    if reverse:
        x1, x2 = end_x, start_x
        marker = "responseArrow"
        dash = ' stroke-dasharray="12 10"'
    else:
        x1, x2 = start_x, end_x
        marker = "requestArrow"
        dash = ""
    midpoint = (x1 + x2) / 2
    circle_y = y
    return (
        f'<line x1="{x1}" y1="{y}" x2="{x2}" y2="{y}" '
        f'stroke="#000000" stroke-width="4"{dash} '
        f'marker-end="url(#{marker})"/>'
        f'<circle cx="{midpoint:.1f}" cy="{circle_y}" r="24" '
        'fill="#ffffff" stroke="#000000" stroke-width="2"/>'
        f'<text x="{midpoint:.1f}" y="{circle_y + 8}" '
        f'font-family="{SERIF_STACK}" font-size="21" font-weight="bold" '
        f'text-anchor="middle" fill="#000000">{html.escape(label)}</text>'
    )


def render_mvc_architecture() -> None:
    width, height = 2400, 1080
    boxes = [
        (35, 300, 255, 390, "USERS", "", ["Student", "Tutor", "Administrator", "Visitor"], 31),
        (
            360,
            230,
            340,
            530,
            "VIEW",
            "React + Vite",
            [
                "Pages and components",
                "Role-based dashboards",
                "Catalog and course pages",
                "Forms and moderation screens",
            ],
            32,
        ),
        (
            810,
            230,
            340,
            530,
            "ROUTES & MIDDLEWARE",
            "Express",
            [
                "REST routes",
                "JWT authentication",
                "Role checks",
                "Input validation",
            ],
            25,
        ),
        (
            1240,
            230,
            340,
            530,
            "CONTROLLER",
            "Express Controllers",
            [
                "Handles requests",
                "Coordinates workflows",
                "Ownership and business rules",
                "Prepares JSON responses",
            ],
            30,
        ),
        (
            1670,
            230,
            340,
            530,
            "MODEL",
            "Data-Access Models",
            [
                "Users and profiles",
                "Tutor posts and bookings",
                "Reviews and reports",
                "Database operations",
            ],
            32,
        ),
        (
            2110,
            300,
            255,
            390,
            "DATABASE",
            "MySQL 8",
            ["Persistent", "marketplace records"],
            29,
        ),
    ]

    svg = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
            f'height="{height}" viewBox="0 0 {width} {height}">'
        ),
        "<title>Mentor Market MVC Architecture and Request Flow</title>",
        (
            "<desc>React View, Express routes and controllers, data-access "
            "models, and MySQL connected by request and response arrows.</desc>"
        ),
        "<defs>",
        (
            '<marker id="requestArrow" markerWidth="16" markerHeight="16" '
            'refX="14" refY="8" orient="auto" markerUnits="userSpaceOnUse">'
            '<path d="M 0 1 L 14 8 L 0 15 Z" fill="#000000"/></marker>'
        ),
        (
            '<marker id="responseArrow" markerWidth="16" markerHeight="16" '
            'refX="14" refY="8" orient="auto" markerUnits="userSpaceOnUse">'
            '<path d="M 0 1 L 14 8 L 0 15 Z" fill="#000000"/></marker>'
        ),
        "</defs>",
        f'<rect x="0" y="0" width="{width}" height="{height}" fill="#ffffff"/>',
        _svg_multiline_text(
            width // 2,
            72,
            ["Mentor Market MVC Architecture and Request Flow"],
            size=48,
            line_height=54,
            weight="bold",
        ),
        (
            '<rect x="775" y="125" width="1270" height="705" fill="none" '
            'stroke="#666666" stroke-width="3" stroke-dasharray="14 10"/>'
        ),
        _svg_multiline_text(
            1410,
            165,
            ["NODE.JS + EXPRESS BACKEND"],
            size=27,
            line_height=32,
            weight="bold",
        ),
    ]

    for x, y, box_width, box_height, title, subtitle, lines, title_size in boxes:
        svg.append(
            _architecture_box(
                x,
                y,
                box_width,
                box_height,
                title,
                subtitle,
                lines,
                title_size=title_size,
            )
        )

    gaps = [
        (290, 360),
        (700, 810),
        (1150, 1240),
        (1580, 1670),
        (2010, 2110),
    ]
    for index, (start, end) in enumerate(gaps, start=1):
        svg.append(_connector(start, end, 385, str(index)))
        svg.append(_connector(start, end, 605, f"R{index}", reverse=True))

    svg.extend(
        [
            _svg_multiline_text(
                45,
                895,
                [
                    "REQUEST: 1 User action   2 Axios HTTP request (JSON + JWT)   "
                    "3 Authenticated and validated request   4 Domain/CRUD operation   "
                    "5 Parameterized SQL"
                ],
                size=24,
                line_height=32,
                anchor="start",
                weight="bold",
            ),
            _svg_multiline_text(
                45,
                950,
                [
                    "RESPONSE: R5 Rows or transaction result   R4 Records or operation result   "
                    "R3 Status and response data   R2 HTTP JSON response   R1 Rendered page and feedback"
                ],
                size=24,
                line_height=32,
                anchor="start",
                weight="bold",
            ),
            _svg_multiline_text(
                45,
                1015,
                [
                    "The React View never communicates directly with the Model or MySQL database."
                ],
                size=23,
                line_height=30,
                anchor="start",
            ),
            "</svg>",
        ]
    )

    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    MVC_SVG.write_text("\n".join(svg), encoding="utf-8")
    subprocess.run(
        [
            "rsvg-convert",
            "--width",
            str(width * 2),
            "--height",
            str(height * 2),
            "--background-color",
            "white",
            "--output",
            str(MVC_PNG),
            str(MVC_SVG),
        ],
        check=True,
    )


def render_all() -> tuple[Path, Path]:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    render_class_diagram()
    render_mvc_architecture()
    return CLASS_PNG, MVC_PNG


if __name__ == "__main__":
    for output in render_all():
        print(output)
